name: End-to-End Tests

on: 
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python version to ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r .github/requirements/test_requirements.txt

      - name: e2e tests
        run: |
          python -m pytest tests_e2e