name: Unit Tests

on: 
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python version to ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r .github/requirements/test_requirements.txt

      - name: Lint
        run: |
          python -m flake8 i18ngenerator/ --count --show-source --statistics
      
      - name: Unit tests & e2e tests
        run: |
          python -m coverage run -m pytest tests tests_e2e

      - name: Transform .coverage to lcov format file
        run: |
          coverage-lcov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:

      - uses: actions/checkout@v3

      - name: Set up Python version to ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r .github/requirements/test_requirements.txt
      
      